---
- hosts: all
  user: pi
  become: yes
  roles:
    - rootbackup
    - awsbackup
    - syncdrives
    - diskalert
    - postfix
    - samba
    - transmission

  vars_files:
    - vars/defaults.yml

  tasks:
    - name: set the host name
      hostname: name={{ hostname }}

    - name: mount disks
      mount: name=/mnt/{{ item.key }} fstype=ext4 state=mounted src='UUID={{ item.value.uuid }}'
      with_dict: "{{ external_drives }}"

    - name: install node
      package: name={{ item }} state=latest
      with_items:
        - node
        - npm
