---
- hosts: all
  user: pi
  become: yes
  roles:
    - rootbackup
    - awsbackup
    - syncdrives
    - diskalert

  vars_files:
    - vars/defaults.yml

  tasks:
    - name: set the host name
      hostname: name={{ hostname }}

    - name: mount the external drive, plop
      mount: name=/mnt/plop fstype=ext4 state=mounted src='UUID=8ffed44c-5198-4d49-ab07-3db72c4d8d29'

    - name: mount the other external drive, blorp
      mount: name=/mnt/blorp fstype=ext4 state=mounted src='UUID=4f77ad0f-b0a7-454a-9de8-0c34671f77e0'

    - name: install samba
      package: name={{ item }} state=latest
      with_items:
        - samba
        - samba-common
        - samba-common-bin

    - name: configure samba
      template: src=templates/smb.conf dest=/etc/samba/smb.conf
      register: sambaconfig

    - name: restart samba
      service: name=smbd state=restarted
      when: sambaconfig.changed

    - name: install avahi
      package: name=libnss-mdns state=latest

    - name: tell avahi to advertise samba
      template: src=templates/smb.service dest=/etc/avahi/services/smb.service
      register: avahiconfig

    - name: restart avahi
      service: name=avahi-daemon state=restarted
      when: avahiconfig.changed

    - name: install transmission
      package: name=transmission-daemon state=latest

    - name: stop transmission
      service: name=transmission-daemon state=stopped

    - name: configure transmission
      template: src=templates/transmission-settings.json.j2 dest=/etc/transmission-daemon/settings.json

    - name: start transmission
      service: name=transmission-daemon state=started
