---
- name: install transmission
  package: name=transmission-daemon state=latest

- name: configure transmission
  template: src=transmission-settings.json.j2 dest=/etc/transmission-daemon/settings.json
  register: transmissionconfig

- name: reload transmission
  service: name=transmission-daemon state=reloaded
  when: transmissionconfig.changed
